# Python和Matlab的差异

这里列举了一些Python和Matlab的差异。Python在执行方式上接近于matlab，然而在Tensor的索引方式上会和C++一样。

## 控制语句

In [1]:
for i in range(10):
    if i%2==0:
        print(f"even:{i}")
    else:
        print(f"odd:{i}")

even:0
odd:1
even:2
odd:3
even:4
odd:5
even:6
odd:7
even:8
odd:9


## 创建变量

In [10]:
import numpy as np

N=25
a=np.ones((N,N))
b=np.arange(0,N)

## 变量索引

In [18]:
print("vector B:\n",b)
B=b.reshape((5,5))
print("matrix B:\n",B)
print("matrix B part:\n",B[1:-1,1:-1])

vector B:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
matrix B:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
matrix B part:
 [[ 6  7  8]
 [11 12 13]
 [16 17 18]]


In [19]:
## 张量合并